//Shop

export const GET_DATA_REQUEST_SUCCESS = "GET_DATA_REQUEST_SUCCESS";
export const GET_DATA_REQUEST_FAIL = "GET_DATA_REQUEST_FAIL";
export const GET_DATA_REQUEST = "GET_DATA_REQUEST ";

export const GET_DATA_BY_CATEGORY_REQUEST = "GET_DATA_BY_CATEGORY_REQUEST";
export const GET_DATA_BY_CATEGORY_REQUEST_SUCCESS =
  "GET_DATA_BY_CATEGORY_REQUEST_SUCCESS";
export const GET_DATA_BY_CATEGORY_REQUEST_FAIL =
  "GET_DATA_BY_CATEGORY_REQUEST_FAIL";

//export const SET_PRICE_REQUEST = "SET_PRICE_REQUEST";

//Cart

export const ADD_CART_REQUEST = "ADD_CART_REQUEST";
export const ADD_CART_REQUEST_SUCCESS = "ADD_CART_REQUEST_SUCCESS";
export const ADD_CART_REQUEST_FAIL = "ADD_CART_REQUEST_FAIL";

export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_REQUEST_SUCCESS = "GET_CART_REQUEST_SUCCESS";
export const GET_CART_REQUEST_FAIL = "GET_CART_REQUEST_FAIL";

export const EDIT_CART_REQUEST = "EDIT_CART_REQUEST";
export const EDIT_CART_REQUEST_SUCCESS = "EDIT_CART_REQUEST_SUCCESS";
export const EDIT_CART_REQUEST_FAIL = "EDIT_CART_REQUEST_FAIL";
