//Shop

export const GET_DATA_REQUEST_SUCCESS = "GET_DATA_REQUEST_SUCCESS";
export const GET_DATA_REQUEST_FAIL = "GET_DATA_REQUEST_FAIL";
export const GET_DATA_REQUEST = "GET_DATA_REQUEST ";

export const GET_PRODUCT_BY_CATEGORY_REQUEST =
  "GET_PRODUCT_BY_CATEGORY_REQUEST";
export const GET_PRODUCT_BY_CATEGORY_REQUEST_SUCCESS =
  "GET_PRODUCT_BY_CATEGORY_REQUEST_SUCCESS";
export const GET_PRODUCT_BY_CATEGORY_REQUEST_FAIL =
  "GET_PRODUCT_BY_CATEGORY_REQUEST_FAIL";

//export const SET_PRICE_REQUEST = "SET_PRICE_REQUEST";

//Cart

export const ADD_CART_REQUEST = "ADD_CART_REQUEST";
export const ADD_CART_REQUEST_SUCCESS = "ADD_CART_REQUEST_SUCCESS";
export const ADD_CART_REQUEST_FAIL = "ADD_CART_REQUEST_FAIL";

export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_REQUEST_SUCCESS = "GET_CART_REQUEST_SUCCESS";
export const GET_CART_REQUEST_FAIL = "GET_CART_REQUEST_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_REQUEST_SUCCESS = "DELETE_PRODUCT_REQUEST_SUCCESS";
export const DELETE_PRODUCT_REQUEST_FAIL = "DELETE_PRODUCT_REQUEST_FAIL";
